--> DAY 11 - MAR 28, 2026


--HANDS-ON SESSION

--------------------------------------------------------------------

CREATE DATABASE Day11Database

USE Day11Database

-------------------------

-- Importing CSV file in our Database
-- Object Explorer > Right click on database name > Click on Task > Import flat file
-- next > Browse > open a csv file > Rename the teble name > next > Allow nulls > next > close
-- After importing the .csv files Now we can access the table

SELECT * FROM FactTable
SELECT * FROM LocationTable
SELECT * FROM ProductTable

-------------------------------------------------

--Q1. Display number of states present in the LocationTable

SELECT COUNT(DISTINCT State) AS Number_Of_Unique_States
FROM LocationTable

-- COUNT(column)          → counts rows
-- COUNT(DISTINCT column) → counts unique values
-- COUNT(*)               → counts all rows including NULLs

-- to see the states
SELECT DISTINCT State
FROM LocationTable

-------------------------------------------------

--Q2. How many products are of regular type in ProductTable?

SELECT COUNT(Type) AS Regular_Products
FROM ProductTable
WHERE Type = 'Regular'

-------------------------------------------------

--Q3. Display the details of the product where product type is coffee. 

SELECT * FROM ProductTable
WHERE Product_Type = 'Coffee'

-------------------------------------------------

--Q4. Display the details where total expenses are greater than 40.

SELECT * FROM FactTable
WHERE Total_Expenses > 40

-------------------------------------------------

--Q5. Find out the total profit generated by Colorado state.

-- Using JOIN
SELECT SUM(F.Profit) AS Total_Profit
FROM FactTable F
JOIN LocationTable L
ON F.Area_Code = L.Area_Code
WHERE L.State = 'Colorado'

--Breakdown:
-----------------------------------------------------------------------
--|         Clause               |             Purpose                |
--|------------------------------|------------------------------------|
--| SUM(F.Profit)                | Adds up all profit values          |
--|------------------------------|------------------------------------|
--| JOIN LocationTable           | Links FactTable with LocationTable |
--|------------------------------|------------------------------------|
--| ON F.Area_Code = L.Area_Code | The common key between both tables |
--|------------------------------|------------------------------------|
--| WHERE L.State = 'Colorado'   | Filters only Colorado rows         |
-----------------------------------------------------------------------

-- Why JOIN is needed here?
-- Because:
-- Profit column is in --> FactTable
-- State column is in --> LocationTable
-- Both table have a common column --> Area_Code

-- So without a JOIN, cannot filter by State and sum Profit at the same time


-- Using Sub Query -->

SELECT SUM(Profit) AS Total_Profit FROM FactTable
WHERE Area_Code = (SELECT Area_Code FROM LocationTable WHERE State = 'Colorado')
-- Error

-- If sub query returning more that 1 value then need to use IN instead of =
-- Sub Query is --> 
SELECT Area_Code FROM LocationTable WHERE State = 'Colorado'

-- So the currect answer Using Sub Query is -->
SELECT SUM(Profit) AS Total_Profit FROM FactTable
WHERE Area_Code IN (SELECT Area_Code FROM LocationTable WHERE State = 'Colorado')

-------------------------------------------------

--Q6. Display the average inventory for each ProductId.

SELECT ProductId, AVG(Inventory) AS Avg_Inventory
FROM FactTable
GROUP BY ProductId

-- Using Sub Query
SELECT DISTINCT ProductId,
       (SELECT AVG(Inventory) 
        FROM FactTable F2 WHERE F2.ProductId = F1.ProductId) AS Avg_Inventory
FROM FactTable F1
ORDER BY ProductId

-------------------------------------------------

--Q7. Display the average total expense of each ProductId on an individual Date.

SELECT ProductId, Date, AVG(Total_Expenses) AS Avg_Total_Expenses
FROM FactTable
GROUP BY ProductId, Date
ORDER BY Date

-- Using Sub Query
SELECT DISTINCT ProductId, Date,
       (SELECT AVG(Total_Expenses) 
        FROM FactTable F2 
        WHERE F2.ProductId = F1.ProductId 
        AND F2.Date = F1.Date) AS Avg_Total_Expenses
FROM FactTable F1
ORDER BY Date

-------------------------------------------------

--Q8. Display the rank without any gap to show Sales wise rank

SELECT DENSE_RANK() OVER (ORDER BY Sales DESC) AS Sales_Rank, *
FROM FactTable

--Breakdown:
-- DENSE_RANK()        --> Assigns rank without gaps
-- OVER()              --> Defines the window for ranking
-- ORDER BY Sales DES  --> CRanks from highest to lowest sales

-- With Gap & Without Gap
SELECT ProductId, Profit, Sales, 
RANK() OVER (ORDER BY Sales DESC) AS With_Gap,
DENSE_RANK() OVER (ORDER BY Sales DESC) AS Without_Gap
FROM FactTable

-------------------------------------------------

--Q9. Find the State wise profit and Sales

SELECT L.State, 
       SUM(F.Profit) AS Total_Profit, 
       SUM(F.Sales) AS Total_Sales
FROM FactTable F
JOIN LocationTable L
ON F.Area_Code = L.Area_Code
GROUP BY L.State
ORDER BY L.State

-------------------------------------------------

--Q10. If there is an increase in Sales by 5%, calculate the increased Sales

SELECT ProductId, Profit, Sales,
       Sales + (Sales * 0.05) AS Increased_Sales
FROM FactTable

-- Sales + (Sales * 0.05) = Sales * 1.05

-------------------------------------------------

-- Q11. Create a stored procedure to fetch the result
--      according to the Product_Type from ProductTable

CREATE PROCEDURE GetProductByName
       @Product_Type VARCHAR(50)
AS
BEGIN
       SELECT * FROM ProductTable
       WHERE Product_Type = @Product_Type
END

-- Execute
EXEC GetProductByName 'Coffee'
EXEC GetProductByName 'Espresso'
EXEC GetProductByName 'Herbal Tea'
EXEC GetProductByName 'Tea'

-- Using function
CREATE FUNCTION GetProductByType
       (@Product_Type VARCHAR(50))
RETURNS TABLE
AS
RETURN
       (SELECT * FROM ProductTable
        WHERE Product_Type = @Product_Type)

-- Call the UDF
SELECT * FROM GetProductByType('Coffee')

-------------------------------------------------

-- Q12. Give the total weekly Sales value with Date and ProductId
--      Use ROLLUP to pull data in hierarchical order

SELECT Date, ProductId, 
       SUM(Sales) AS Total_Sales
FROM FactTable
GROUP BY ROLLUP(Date, ProductId)
ORDER BY Date, ProductId

-- To check the week 
SELECT DATEPART(week, Date) AS week_num,
       ProductId,
       SUM(Sales) AS Total_Sales
FROM FactTable
GROUP BY ROLLUP(DATEPART(week, Date), ProductId)
ORDER BY week_num, ProductId

-------------------------------------------------

-- Q13. Display the ASCII value of the fifth character from Product column

SELECT Product, 
       ASCII(SUBSTRING(Product, 5, 1)) AS ASCII_Value
FROM ProductTable

-- OR

SELECT Product, 
       SUBSTRING(Product, 5, 1) AS Character,
       ASCII(SUBSTRING(Product, 5, 1)) AS ASCII_Value
FROM ProductTable

-- In Product column Start at position 5 
-- and use SUBSTRING to Extract only 1 character
