--> DAY 11 - MAR 28, 2026


--HANDS-ON SESSION

--------------------------------------------------------------------

CREATE DATABASE Day11Database

USE Day11Database

-------------------------

-- Importing CSV file in our Database
-- Object Explorer > Right click on database name > Click on Task > Import flat file
-- next > Browse > open a csv file > Rename the teble name > next > Allow nulls > next > close
-- After importing the .csv files Now we can access the table

SELECT * FROM FactTable
SELECT * FROM LocationTable
SELECT * FROM ProductTable

-------------------------

--Q1. Display number of states present in the LocationTable

SELECT COUNT(DISTINCT State) AS Number_Of_Unique_States
FROM LocationTable

-- COUNT(column)          → counts rows
-- COUNT(DISTINCT column) → counts unique values
-- COUNT(*)               → counts all rows including NULLs

-- to see the states
SELECT DISTINCT State
FROM LocationTable


--Q2. How many products are of regular type in ProductTable?

SELECT COUNT(Type) AS Regular_Products
FROM ProductTable
WHERE Type = 'Regular'


--Q3. Display the details of the product where product type is coffee. 

SELECT * FROM ProductTable
WHERE Product_Type = 'Coffee'


--Q4. Display the details where total expenses are greater than 40.

SELECT * FROM FactTable
WHERE Total_Expenses > 40



--Q5. Find out the total profit generated by Colorado state.

-- Using JOIN
SELECT SUM(F.Profit) AS Total_Profit
FROM FactTable F
JOIN LocationTable L
ON F.Area_Code = L.Area_Code
WHERE L.State = 'Colorado'

--Breakdown:
---------------------------------------------------------------------
| Clause                       | Purpose                            |
|------------------------------|------------------------------------|
| SUM(F.Profit)                | Adds up all profit values          |
| JOIN LocationTable           | Links FactTable with LocationTable |
| ON F.Area_Code = L.Area_Code | The common key between both tables |
| WHERE L.State = 'Colorado'   | Filters only Colorado rows         |
---------------------------------------------------------------------

-- Why JOIN is needed here?
-- Because:
-- Profit lives in        → FactTable
-- State name lives in    → LocationTable
-- They are connected via → Area_Code

-- So without a JOIN, cannot filter by State and sum Profit at the same time


-- Using Sub Query -->

SELECT SUM(Profit) AS Total_Profit FROM FactTable
WHERE Area_Code = (SELECT Area_Code FROM LocationTable WHERE State = 'Colorado')
-- Error

-- If sub query returning more that 1 value then need to use IN instead of =
-- Sub Query is --> 
SELECT Area_Code FROM LocationTable WHERE State = 'Colorado'

-- So the currect answer Using Sub Query is -->
SELECT SUM(Profit) AS Total_Profit FROM FactTable
WHERE Area_Code IN (SELECT Area_Code FROM LocationTable WHERE State = 'Colorado')



--Q6. Display the average inventory for each ProductId.

SELECT ProductId, AVG(Inventory) AS Avg_Inventory
FROM FactTable
GROUP BY ProductId

-- Using Sub Query
SELECT DISTINCT ProductId,
       (SELECT AVG(Inventory) 
        FROM FactTable F2 WHERE F2.ProductId = F1.ProductId) AS Avg_Inventory
FROM FactTable F1
ORDER BY ProductId



--Q7. Display the average total expense of each ProductId on an individual Date.

SELECT ProductId, Date, AVG(Total_Expenses) AS Avg_Total_Expenses
FROM FactTable
GROUP BY ProductId, Date
ORDER BY Date

-- Using Sub Query
SELECT DISTINCT ProductId, Date,
       (SELECT AVG(Total_Expenses) 
        FROM FactTable F2 
        WHERE F2.ProductId = F1.ProductId 
        AND F2.Date = F1.Date) AS Avg_Total_Expenses
FROM FactTable F1
ORDER BY Date